storage:
  type: file
  host: localhost
  port: 3306
  user: bench
  pass: A_secure_password
  database: orange_bench

resource-pack:
  client-addr:
    host: 114.51.41.91
    port: 9810
    path: /assets/pack.zip
  builtin-distributor:
    enabled: true
    host: 0.0.0.0
    port: 25580
    path: /resourcepacks/
